version: '3'
services:
  ethereum-api:
    image: ethereum-api
    volumes: 
      - "./routes:/opt/app/routes"
      - "./temp:/opt/app/temp"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"